# Generated by Django 5.1.7 on 2025-04-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_remove_productimage_image_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
