# Generated by Django 5.1.7 on 2025-05-23 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_variant_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Enter % discount (e.g., 10 for 10%)'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_offer',
            field=models.BooleanField(default=False, help_text='Is there an active offer?'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='offer_title',
            field=models.CharField(blank=True, help_text="Offer name like 'Summer Sale'", max_length=100, null=True),
        ),
    ]
