# Generated by Django 5.1.7 on 2025-10-28 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0012_coupon_is_referral_reward_coupon_specific_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Enter % discount (e.g., 10 for 10%)'),
        ),
        migrations.AddField(
            model_name='genre',
            name='is_offer',
            field=models.BooleanField(default=False, help_text='Is there an active offer?'),
        ),
        migrations.AddField(
            model_name='genre',
            name='offer_title',
            field=models.CharField(blank=True, help_text="Offer name like 'Summer Sale'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 28, 10, 22, 40, 522238, tzinfo=datetime.timezone.utc)),
        ),
    ]
