# Generated by Django 5.1.7 on 2025-10-28 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_genre_discount_percentage_genre_is_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 28, 10, 35, 16, 608133, tzinfo=datetime.timezone.utc)),
        ),
    ]
