# Generated by Django 5.1.7 on 2025-06-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_order_cancel_reson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancel_reson',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
