# Generated by Django 5.1.7 on 2025-06-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_order_cancel_reson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cancel_reson',
            new_name='cancel_reason',
        ),
    ]
