# Generated by Django 5.1.7 on 2025-07-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_address_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=' ', editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
