# Generated by Django 5.1.7 on 2025-08-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
