# Generated by Django 5.1.7 on 2025-08-17 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
