# Generated by Django 5.1.7 on 2025-10-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_order_razorpay_order_id_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_amount',
            new_name='unit_price',
        ),
    ]
