# Generated by Django 5.1.7 on 2025-10-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_total_amount_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
