# Generated by Django 5.1.7 on 2025-10-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_orderitem_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
