# Generated by Django 5.1.7 on 2025-11-02 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_customuser_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('razorpay', 'Razorpay'), ('cod', 'COD'), ('refund', 'Refund'), ('wallet_addition', 'Wallet Addition')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='completed', max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['-transaction_date'], name='users_trans_transac_12a4ad_idx'), models.Index(fields=['transaction_type'], name='users_trans_transac_dd58bb_idx'), models.Index(fields=['user', '-transaction_date'], name='users_trans_user_id_b50875_idx')],
            },
        ),
    ]
