# Generated by Django 5.1.7 on 2025-11-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_wallettransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
