# Generated by Django 5.1.7 on 2025-11-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_transaction'),
        ('users', '0032_customersupport'),
    ]

    operations = [
    ]
