# Generated by Django 5.1.7 on 2025-11-11 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_merge_0030_transaction_0032_customersupport'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='users.orderitem'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('cod', 'COD'), ('refund', 'Refund'), ('wallet_addition', 'Wallet Addition'), ('wallet_debit', 'Wallet Debit')], max_length=50),
        ),
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
