# Generated by Django 5.1.7 on 2025-11-16 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_transaction_order_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('seller_name', models.CharField(default='Book Hive Pvt Ltd', max_length=200)),
                ('seller_address', models.CharField(default='24/B MG Road, Bangalore', max_length=500)),
                ('seller_phone', models.CharField(default='7907302778', max_length=20)),
                ('seller_email', models.EmailField(default='info@bookhive.com', max_length=254)),
                ('seller_gstin', models.CharField(default='29ABCDE1234F1Z5', max_length=20)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_address', models.TextField()),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('snapshot_order_id', models.CharField(max_length=50)),
                ('order_date', models.DateField()),
                ('payment_method', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='users.order')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
    ]
