# Generated by Django 5.1.7 on 2025-11-16 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('credit_note_date', models.DateField(auto_now_add=True)),
                ('original_invoice_number', models.CharField(max_length=50)),
                ('original_invoice_date', models.DateField()),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_email', models.EmailField(max_length=254)),
                ('seller_name', models.CharField(default='Book Hive Pvt Ltd', max_length=200)),
                ('seller_address', models.CharField(default='24/B MG Road, Bangalore', max_length=500)),
                ('seller_phone', models.CharField(default='7907302778', max_length=20)),
                ('seller_email', models.EmailField(default='info@bookhive.com', max_length=254)),
                ('seller_gstin', models.CharField(default='29ABCDE1234F1Z5', max_length=20)),
                ('item_name', models.CharField(max_length=500)),
                ('quantity_returned', models.PositiveIntegerField()),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_reversal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_refund', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_payment_method', models.CharField(max_length=100)),
                ('refund_method', models.CharField(default='Wallet', max_length=100)),
                ('reason', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='users.invoice')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note', to='users.orderitem')),
            ],
            options={
                'ordering': ['-credit_note_date', '-created_at'],
            },
        ),
    ]
