# Generated by Django 5.1.7 on 2025-11-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_creditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_items',
            field=models.JSONField(default=list, editable=False),
        ),
    ]
