from . import views
from django.urls import path

urlpatterns = [
    path('admin_signin',views.admin_signin,name='admin_signin'),
    path('admin_dashboard',views.admin_dashboard,name='admin_dashboard'),
    path('books',views.books,name='books'),
    path('admin_logout',views.admin_logout,name='admin_logout'),
    path('genre',views.genre,name='genre'),
    path('change_genre_status',views.change_genre_status,name='change_genre_status'),
    path('genre_edit',views.genre_edit,name='genre_edit'),
    path('genre_edit_post',views.genre_edit_post,name='genre_edit_post'),
    path('add_new_book',views.add_new_book,name='add_new_book'),
    path('view_variant/<int:book_id>/',views.view_variant,name='view_variant'),
    path('variant_delete',views.variant_delete,name='variant_delete'),
    path('add_variant/<int:book_id>/',views.add_variant,name='add_variant'),
    path('customer_details',views.customer_details,name='customer_details'),
    path('change_user_status',views.change_user_status,name='change_user_status'),
    path('user_search',views.user_search,name='user_search'),
    path('genre_search',views.genre_search,name='genre_search'),
    path('book_edit',views.book_edit,name='book_edit'),
    path('book_edit_post',views.book_edit_post,name='book_edit_post'),
    path('book_delete',views.book_delete,name='book_delete'),
    path('variant_edit',views.variant_edit,name='variant_edit'),
    path('variant_edit_post',views.variant_edit_post,name='variant_edit_post'),
    path('admin_order',views.admin_order,name='admin_order'),
    path('update_order_item_status/<int:order_item_id>',views.update_order_item_status,name='update_order_item_status'),
    path('admin_order_details/<int:order_id>/',views.admin_order_details, name='admin_order_details'),
    path('admin_review',views.admin_review, name='admin_review'),
    path('toggle_review_status/<int:review_id>/',views.toggle_review_status, name='toggle_review_status'),
]